const animaisPorSecao = {
    cachorros: [
        {
            nome: 'Francisca (Chica)',
            detalhes: 'Grande | Fêmea | 11 anos',
            infos: 'Francisca (Chica) é calma, vive bem em casa com quintal e se dá bem com cães machos.',
            imagem: 'fotos animais/FRANCISCA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=0',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Calmo'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Dudu',
            detalhes: 'Grande | Macho | 11 anos',
            infos: 'Dudu é calmo, vive bem em casa com quintal e se dá bem com cães machos.',
            imagem: 'fotos animais/DUDU.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=1',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Calmo'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Maria Laura (Lala)',
            detalhes: 'Grande | Fêmea | 11 anos',
            infos: 'Maria Laura (Lala) é agitada, vive bem em casa com quintal e se dá bem com cães machos.',
            imagem: 'fotos animais/MARIA LAURA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=2',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agitado'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Linda Inês',
            detalhes: 'Grande | Fêmea | 11 anos',
            infos: 'Linda Inês é agitada, vive bem em casa com quintal e se dá bem com cães fêmeas e machos.',
            imagem: 'fotos animais/LINDA INÊS.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=3',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agitado'],
            sociavel: ['Cão fêmea', 'Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Bob',
            detalhes: 'Grande | Macho | 13 anos',
            infos: 'Bob é calmo, vive bem em casa com quintal e se dá bem com cães fêmeas e machos.',
            imagem: 'fotos animais/BOB.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=4',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Calmo'],
            sociavel: ['Cão fêmea', 'Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Paçoca',
            detalhes: 'Pequeno | Macho | 16 anos',
            infos: 'Paçoca é calmo, medroso e independente, sociável com todos, exceto gatos e outros animais, vive bem em casa ou apartamento, é cego e merece uma adoção especial.',
            imagem: 'fotos animais/PAÇOCA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=5',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Calmo', 'Medroso', 'Independente'],
            sociavel: ['Criança', 'Desconhecidos', 'Idosos', 'Cão fêmea', 'Cão macho'],
            ambiente: ['Casa', 'Apartamento']
        },
        {
            nome: 'Victoria',
            detalhes: 'Pequeno | Fêmea | 6 meses',
            infos: 'Victoria é tímida, medrosa e brincalhona, sociável com gatos e cães, e vive bem em casas com quintal.',
            imagem: 'fotos animais/VICTORIA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=6',
            cuidados: ['Vermifugado'],
            temperamento: ['Tímido', 'Medroso', 'Brincalhão'],
            sociavel: ['Gatos', 'Cão fêmea', 'Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Bebel',
            detalhes: 'Pequeno | Fêmea | 5/6 meses',
            infos: 'Bebel é medrosa e brincalhona, sociável com todos, exceto outros animais, e vive bem em casa com quintal.',
            imagem: 'fotos animais/BEBEL.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=7',
            cuidados: ['Vermifugado', 'Vacinado'],
            temperamento: ['Medroso', 'Brincalhão'],
            sociavel: ['Crianças', 'Desconhecidos', 'Idosos', 'Gatos', 'Cão fêmea', 'Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Bob',
            detalhes: 'Grande | Macho | 5 anos',
            infos: 'Bob é independente, sociável com cães machos, e vive bem em casa com quintal.',
            imagem: 'fotos animais/BOB-1.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=8',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Independente'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Mike',
            detalhes: 'Grande | Macho | 6 anos',
            infos: 'Mike é medroso, sociável com cães machos, e vive bem em casa com quintal.',
            imagem: 'fotos animais/MIKE.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=9',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Medroso'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Tom',
            detalhes: 'Grande | Macho | 6 anos',
            infos: 'Tom é agressivo, sociável com outros animais, e vive bem em casa com quintal, ele é bravo com cães machos e pessoas.',
            imagem: 'fotos animais/TOM.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=10',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Outros animais'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Pintado',
            detalhes: 'Médio | Macho | 3 anos',
            infos: 'Pintado é agitado, sociável com cães fêmeas, e vive bem em casa com quintal, suas pernas de trás são curtas devido a cirurgia.',
            imagem: 'fotos animais/PINTADO.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=11',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agitado'],
            sociavel: ['Cão fêmea'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Scobby',
            detalhes: 'Grande | Macho | 8 anos',
            infos: 'Scobby é agressivo, sociável com cães fêmeas, e vive bem em casa com quintal.',
            imagem: 'fotos animais/SCOBBY.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=12',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Cão fêmea'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Princesa',
            detalhes: 'Grande | Fêmea | 5 anos',
            infos: 'Princesa é agressiva, sociável com outros animais, e vive bem em casa com quintal, ela é brava com cães, gatos e pessoas.',
            imagem: 'fotos animais/PRINCESA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=13',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Outros animais'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Vitoria',
            detalhes: 'Grande | Fêmea | 6 anos',
            infos: 'Vitoria é medrosa, sociável com cães machos, e vive bem em casa com quintal.',
            imagem: 'fotos animais/VITORIA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=14',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Medroso'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Neymar',
            detalhes: 'Grande | Macho | 6 anos',
            infos: 'Neymar é agressivo, sociável com cães fêmeas, e vive bem em casa com quintal.',
            imagem: 'fotos animais/NEYMAR.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=15',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Cão fêmea'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Shakira',
            detalhes: 'Grande | Fêmea | 6 anos',
            infos: 'Shakira é agressiva, sociável com cães machos, e vive bem em casa com quintal.',
            imagem: 'fotos animais/SHAKIRA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=16',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        },
        {
            nome: 'Shera',
            detalhes: 'Médio | Fêmea | 6 anos',
            infos: 'Shera é agressiva, sociável com cães machos, e vive bem em casa com quintal.',
            imagem: 'fotos animais/SHERA.png',
            alt: 'Cachorro disponível para adoção',
            pagina: 'animais/cachorros.html?secao=cachorros&indice=17',
            cuidados: ['Castrado', 'Vermifugado', 'Vacinado'],
            temperamento: ['Agressivo'],
            sociavel: ['Cão macho'],
            ambiente: ['Casa com quintal']
        }
    ],
    gatos: [],
    cavalos: []
};
